### ISSUE TITLE
Makefile formatting

### ISSUE THREAD

**Issue by ricardotaborda** [ProgToolsChemStruct/chemistry_structure_shit#16]
Makefiles are tricky in the sense that different systems may ask for different things, and the "make" program that runs the makefile is sometimes picky or needy.  So, two issues to solve:

1.
It is better if you could rename "makefile" to "Makefile", as that would allow all "make" programs in linux-based systems to recognize it without the need of a file identifier "-f" instruction. You can do this with the instruction "git mv makefile Makefile" (I know it works on Mac and Linux, not sure if Windows).

2.
Some "make" programs will complain if a proper "separator" is not used. In the current version in the repository, the spacing in front of lines 8, 11, 14, and 17 are four spaces. The make program requires it to be a tab instead of spaces. So please change it to tabs in each of this lines.

**Comment by kchrbnnt** [comment]
Done

**Comment by ricardotaborda** [comment]
Point 1 was solved. But not point 2. Double check your text editor and make sure those lines have a tab in front as opposed to 4 spaces.

**Comment by kchrbnnt** [comment]
My text editor on Linux (Nedit) shows tabs at those places, but the github text editor converts my tabs into 4 spaces.

**Comment by kchrbnnt** [comment]
I think I fixed it

**Comment by ricardotaborda** [comment]
Someone edited the Makefile and re-introduced the bug. The second lines in the Makefile should always be tabs.

**Comment by kchrbnnt** [comment]
I fixed it

**Comment by ricardotaborda** [comment]
Close this issue ticket
