### ISSUE TITLE
Meet with Dr. Taborda

### ISSUE THREAD

**Issue by kchrbnnt** [ProgToolsChemStruct/chemistry_structure_shit#23]
Dr. Taborda,
Did you say that you wanted to meet with our group regarding our project?

**Comment by ricardotaborda** [comment]
Team,
I mentioned during the presentation that Tom gave to the class last week that given what you were trying to do it would be of interest to figure if a certain data structure could help you do it in a more interesting way, and then suggested you may want to meet with me to discuss it. But that is up to you. If you want to do it, I'll be happy to meet with you.

**Comment by ricardotaborda** [comment]
It seems you can close this ticket.
