### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by ricardotaborda** [ProgToolsChemStruct/chemistry_structure_shit#3]
Add the executable to the .gitignore file so that when one compiles and checks the status in git, it does not list executable as an untracked file.

**Comment by ricardotaborda** [comment]
This is solved by adding the word:

main

to the .gitignore file.

**Comment by kchrbnnt** [comment]
Is it customary to respond with thank you on these comments? Just curious.

**Comment by ricardotaborda** [comment]
Sure... or a simple: "done" or "got it" and then you click the "close" button, which will close the issue and move it to the section of closed/archived issues. Which is where you look for stuff before posting a new issue in case you find someone who had something similar before.
