### ISSUE TITLE
long lines

### ISSUE THREAD

**Issue by ricardotaborda** [ProgToolsChemStruct/chemistry_structure_shit#30]
Lines should not be longer than 80 or 100 columns.

**Comment by kchrbnnt** [comment]
In dihedral_angle.h, line 24 is really long. How might I go about shortening it without losing important information?

**Comment by ricardotaborda** [comment]
How about...

```c
double tau_ijkl(
    double ex_ji, double ey_ji, double ez_ji, 
    double ex_jk, double ey_jk, double ez_jk, 
    double ex_kl, double ey_kl, double ez_kl, 
    double phi_ijk, double phi_jkl);
```

**Comment by ricardotaborda** [comment]
Since we are talking about this, and although I am sure the meaning is different in chemistry than in engineering or seismology, it seems to me somewhat obvious that the term `e` is a `3x3` tensor. Wouldn't it make more sense to have a two-dimensional array for that?

**Comment by kchrbnnt** [comment]
I think that I need to have it as a 2D array that references the vector created in extraction.cpp, but I'm still working on understanding the code in extraction.cpp

**Comment by hclozano** [comment]
fixed in angles.cpp pull request #66
