### ISSUE TITLE
Add comment at the end of header files

### ISSUE THREAD

**Issue by ricardotaborda** [ProgToolsChemStruct/chemistry_structure_shit#32]
At the end of the header files, it is a good practice to add a comment indicating the connection of the `endif` tag. Like this:

```c
#ifndef BOND_ANGLE_H
#define BOND_ANGLE_H
...
#endif //BOND_ANGLE_H
```

**Comment by kchrbnnt** [comment]
Done

**Comment by ricardotaborda** [comment]
I do not see this done, and I do not see any pending pull request.

**Comment by kchrbnnt** [comment]
Sorry, I forgot to do a pull request after I fixed it. Is it done now?

**Comment by hclozano** [comment]
Done throughout project.
