### ISSUE TITLE
Code is not compiling

### ISSUE THREAD

**Issue by ricardotaborda** [ProgToolsChemStruct/chemistry_structure_shit#35]
Latest pull request and merge by @hclozano damaged the code. The code is not compiling. Never commit a version to the group's main repository that does not compile.

**Comment by tsmmers1** [comment]
Latest pull request (pull request #42 ) merged code from both Kate and I to resolve some (but not all) of the compiling issues.  Compiling issues not resolved were commented-out. @hclozano please see linked pull request for info on which of your .h files had things commented-out.

**Comment by hclozano** [comment]
I fixed elements.h so it compiles. I am working on making it so I can do a pull request that will automatically merge because there are problems right now.

**Comment by hclozano** [comment]
Okay. It compiles and I fixed it so it would't have any conflicts when merging and it has been merged.
