### ISSUE TITLE
comments needed in extraction.cpp

### ISSUE THREAD

**Issue by kchrbnnt** [ProgToolsChemStruct/chemistry_structure_shit#37]
I'm not really clear on what these lines are doing:

while (getline(cleancoords,line)) {
        sub_array.clear();
        stringstream newstring(line);

        while (getline(newstring, sub_line, ',')) {
            sub_array.push_back(sub_line);
        }
        array.push_back(sub_array);

Could you please add come comments to clarify? Thank you.

**Comment by kchrbnnt** [comment]
and by those lines I mean lines 108-116

**Comment by kchrbnnt** [comment]
also ++i and ++j need to be changed to i++ and j++

**Comment by tsmmers1** [comment]
I corrected the i++ and j++ and added some Doxygen information regarding what the code does in my local repository.  I will do a pull request once the main repo is fixed and properly compiling.

But (roughly - and in non-proper lingo) what happens is, with example data:

C,1,0.000000,1.1111111,2.2222222
H,-1,3.33333,4.4444444,5.5555555
...
```
while (getline(cleancoords,line)) {
sub_array.clear();
stringstream newstring(line);
```
The first part extracts a chunk of text delimited by the newfunction \n and stores it specifically as a string, giving the data:  C,1,0.000000,1.1111111,2.2222222.
 ```
   while (getline(newstring, sub_line, ',')) {
        sub_array.push_back(sub_line);
    }
    array.push_back(sub_array);
```
The second part further divides the string based upon the specified delimiter, the comma.  It takes these new chunks (e.g. C for the first chunk, 1 for the second chunk, 0.000000 for the third chunk, etc.) and stores them in a temporary vector sub_array.  This _sub_array_ is then added to the end of the main vector _array_ before the cycle repeats with the next line H,-1,3.33333,4.4444444,5.5555555.
