### ISSUE TITLE
doxy and gitignore

### ISSUE THREAD

**Issue by ricardotaborda** [ProgToolsChemStruct/chemistry_structure_shit#4]
Add the html and latex directories to the gitignore file, so that when documentation is generated, they are not listed as untracked by git status

**Comment by kchrbnnt** [comment]
I'm not sure exactly how to make it so git ignores the html and latex directories. Do I add html/** and latex/** to the gitignore file? Or do I add *.html and *.tex to the gitignore file?

When you say "add the executable to the .gitignore file," do you mean the *.out executable? I'm not sure what I need to add in order "not list executable as an untracked file."

**Comment by ricardotaborda** [comment]
The first part is simply about adding the words:

html
latex

in the .gitignore file.

The second part belongs to a different issue thread.
