### ISSUE TITLE
documentation main.h

### ISSUE THREAD

**Issue by ricardotaborda** [ProgToolsChemStruct/chemistry_structure_shit#6]
Document the gaussian_output with doxygen interpretable info

**Comment by kchrbnnt** [comment]
I'm confused as to why we need a main.h file?

**Comment by ricardotaborda** [comment]
The decision of creating a main.h file is yours. I look at it and found you had defined a class in there.  And I created this issue ticket just to request that you document it for doxygen purposes. If you later decide to move this class to a different file and main.h becomes obsolete, that would be fine with me.

**Comment by hclozano** [comment]
Deleted main.h as it was no loner necessary. Thomas deleted it in pull #55 I believe and I accidentally brought it back in pull #59. Kate re-deleted and committed it in pull #63.
