### ISSUE TITLE
unnecessary declaration

### ISSUE THREAD

**Issue by ricardotaborda** [ProgToolsChemStruct/chemistry_structure_shit#68]
In `angles.cpp`, line 17, you have

```
extern int number_atoms;
```

But it is never used as a global variable here, because all functions that use it take it as a parameter. So this is unnecessary.

**Comment by ricardotaborda** [comment]
There are also several unnecessary declarations (variables declared but not used) in `bond_number.cpp`

**Comment by hclozano** [comment]
Removed pull request #73
